name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (e.g., dev, prod)'
        required: true
        default: 'dev'

concurrency:
  group: terraform-destroy-${{ github.ref }}
  cancel-in-progress: false

env:
  TF_IN_AUTOMATION: "true"
  ARM_USE_AZUREAD: "true"
  ARM_USE_OIDC: "true"
  TF_INPUT: "false"

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://portal.azure.com/
    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (Apply SPN via OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_APPLY }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure Remote State Backend Exists (Azure CLI)
        uses: azure/CLI@v2
        with:
          inlineScript: |
            set -e
            RG_NAME="${{ secrets.TFSTATE_RG_NAME }}"
            SA_NAME="${{ secrets.TFSTATE_SA_NAME }}"
            CONTAINER_NAME="${{ secrets.TFSTATE_CONTAINER_NAME }}"
            az group create -n "$RG_NAME" -l ${{ secrets.TFSTATE_LOCATION }}
            az storage account show -n "$SA_NAME" -g "$RG_NAME" >/dev/null 2>&1 || \
              az storage account create -n "$SA_NAME" -g "$RG_NAME" -l ${{ secrets.TFSTATE_LOCATION }} \
                --sku Standard_LRS --encryption-services blob
            az storage container show --account-name "$SA_NAME" --name "$CONTAINER_NAME" --auth-mode login >/dev/null 2>&1 || \
              az storage container create --account-name "$SA_NAME" --name "$CONTAINER_NAME" --auth-mode login

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Terraform Init (AAD + OIDC backend)
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.TFSTATE_RG_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_SA_NAME }}" \
            -backend-config="container_name=${{ secrets.TFSTATE_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.TFSTATE_KEY }}" \
            -backend-config="use_azuread_auth=true" \
            -backend-config="use_oidc=true"

      - name: Terraform Destroy
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_environment: ${{ github.event.inputs.environment }}
        run: |
          set -euo pipefail
          terraform version
          echo "Destroying infrastructure for environment: ${{ github.event.inputs.environment }}"
          terraform destroy -auto-approve
